# Generated by Django 6.1 on 2026-09-01 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityBagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی شده'), ('active', 'فعال'), ('resolving', 'در حال تسویه'), ('finished', 'تمام شده')], default='scheduled', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('total_contributed', models.PositiveIntegerField(default=0)),
                ('total_requested', models.PositiveIntegerField(default=0)),
                ('charity_succeeded', models.BooleanField(blank=True, null=True)),
                ('settlement_started_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='charity_bag_positive_window'), models.UniqueConstraint(fields=('starts_at',), name='charity_bag_unique_start'), models.CheckConstraint(condition=models.Q(models.Q(('charity_succeeded__isnull', True), ('settled_at__isnull', True), ('status__in', ['scheduled', 'active', 'resolving'])), models.Q(('charity_succeeded__isnull', False), ('settled_at__isnull', False), ('status', 'finished')), _connector='OR'), name='charity_bag_settlement_state_consistent')],
            },
        ),
        migrations.CreateModel(
            name='CharityBagParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('contribute', 'کمک به خیریه'), ('request', 'درخواست از خیریه')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('stake_deducted', models.PositiveIntegerField()),
                ('final_payout', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.charitybagevent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charity_bag_participations', to='teams.team')),
            ],
            options={
                'ordering': ['submitted_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('event', 'team'), name='charity_bag_one_entry_per_team'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='charity_bag_amount_positive'), models.CheckConstraint(condition=models.Q(('stake_deducted', models.F('amount'))), name='charity_bag_stake_matches_amount')],
            },
        ),
    ]
