# Generated by Django 6.1 on 2026-09-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_charitybagevent_charitybagparticipation'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentipedeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('player_one_reward', models.PositiveBigIntegerField(default=50)),
                ('player_two_reward', models.PositiveBigIntegerField(default=200)),
                ('actions_completed', models.PositiveIntegerField(default=0)),
                ('player_one_final_payout', models.PositiveBigIntegerField(default=0)),
                ('player_two_final_payout', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting_for_players', 'در انتظار بازیکنان'), ('active', 'فعال'), ('finished', 'تمام شده')], default='active', max_length=19)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_centipede_games', to='teams.team')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centipede_games_as_player_one', to='teams.team')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centipede_games_as_player_two', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_centipede_games', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CentipedeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('round_number', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('take', 'بردار'), ('continue', 'ادامه بده')], max_length=8)),
                ('displayed_reward', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centipede_decisions', to='teams.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='events.centipedegame')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(('player_one', models.F('player_two')), _negated=True), name='centipede_two_distinct_players'),
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='centipede_round_positive'),
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(('player_one_reward__gte', 50), ('player_two_reward__gte', 200)), name='centipede_rewards_minimum'),
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(('active_player', models.F('player_one')), ('active_player', models.F('player_two')), ('active_player__isnull', True), _connector='OR'), name='centipede_active_is_player'),
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(('winner', models.F('player_one')), ('winner', models.F('player_two')), ('winner__isnull', True), _connector='OR'), name='centipede_winner_is_player'),
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_player__isnull', True), ('finished_at__isnull', True), ('player_one_final_payout', 0), ('player_two_final_payout', 0), ('status', 'waiting_for_players'), ('winner__isnull', True)), models.Q(('active_player__isnull', False), ('finished_at__isnull', True), ('player_one_final_payout', 0), ('player_two_final_payout', 0), ('status', 'active'), ('winner__isnull', True)), models.Q(('active_player__isnull', True), ('finished_at__isnull', False), ('status', 'finished'), ('winner__isnull', False)), _connector='OR'), name='centipede_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='centipedegame',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player_one_final_payout__gt', 0), ('player_two_final_payout', 0), ('winner', models.F('player_one'))), models.Q(('player_one_final_payout', 0), ('player_two_final_payout__gt', 0), ('winner', models.F('player_two'))), ('winner__isnull', True), _connector='OR'), name='centipede_payout_matches_winner'),
        ),
        migrations.AddConstraint(
            model_name='centipededecision',
            constraint=models.UniqueConstraint(fields=('game', 'sequence'), name='centipede_decision_sequence'),
        ),
        migrations.AddConstraint(
            model_name='centipededecision',
            constraint=models.UniqueConstraint(fields=('game', 'round_number', 'actor'), name='centipede_one_decision_per_player_round'),
        ),
        migrations.AddConstraint(
            model_name='centipededecision',
            constraint=models.CheckConstraint(condition=models.Q(('displayed_reward__gt', 0), ('round_number__gte', 1), ('sequence__gte', 1)), name='centipede_decision_values_positive'),
        ),
    ]
