# Generated by Django 6.1 on 2026-09-02 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_centipedegame_centipededecision_and_more'),
        ('teams', '0002_team_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympicsMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_game', models.CharField(choices=[('coin_near_wall', 'سکه نزدیک دیوار'), ('marble_target', 'تیله هدف')], max_length=16)),
                ('scoring_zones', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('created', 'ساخته شده'), ('active', 'در حال اجرا'), ('waiting_for_result', 'در انتظار نتیجه'), ('tiebreak', 'تساوی\u200cشکن'), ('finished', 'تمام شده')], default='created', max_length=18)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olympics_matches_as_player_one', to='teams.team')),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olympics_matches_as_player_two', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_olympics_matches', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OlympicsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('round_number', models.PositiveIntegerField()),
                ('player_one_attempts', models.JSONField(blank=True, default=list)),
                ('player_two_attempts', models.JSONField(blank=True, default=list)),
                ('player_one_total', models.PositiveIntegerField(blank=True, null=True)),
                ('player_two_total', models.PositiveIntegerField(blank=True, null=True)),
                ('player_one_best_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('player_two_best_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('outcome', models.CharField(choices=[('player_one', 'بازیکن اول'), ('player_two', 'بازیکن دوم'), ('tie', 'تساوی')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.olympicsmatch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_olympics_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='olympicsmatch',
            constraint=models.CheckConstraint(condition=models.Q(('player_one', models.F('player_two')), _negated=True), name='olympics_two_distinct_players'),
        ),
        migrations.AddConstraint(
            model_name='olympicsmatch',
            constraint=models.CheckConstraint(condition=models.Q(('winner', models.F('player_one')), ('winner', models.F('player_two')), ('winner__isnull', True), _connector='OR'), name='olympics_winner_is_player'),
        ),
        migrations.AddConstraint(
            model_name='olympicsmatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('status', 'created'), ('winner__isnull', True)), models.Q(('finished_at__isnull', True), ('started_at__isnull', False), ('status__in', ['active', 'waiting_for_result', 'tiebreak']), ('winner__isnull', True)), models.Q(('finished_at__isnull', False), ('started_at__isnull', False), ('status', 'finished'), ('winner__isnull', False)), _connector='OR'), name='olympics_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='olympicsresult',
            constraint=models.UniqueConstraint(fields=('match', 'round_number'), name='olympics_one_result_per_round'),
        ),
        migrations.AddConstraint(
            model_name='olympicsresult',
            constraint=models.CheckConstraint(condition=models.Q(('round_number__gte', 1)), name='olympics_result_round_positive'),
        ),
        migrations.AddConstraint(
            model_name='olympicsresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player_one_total__isnull', True), ('player_two_total__isnull', True)), models.Q(('player_one_total__isnull', False), ('player_two_total__isnull', False)), _connector='OR'), name='olympics_totals_pair'),
        ),
        migrations.AddConstraint(
            model_name='olympicsresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player_one_best_distance__isnull', True), ('player_two_best_distance__isnull', True)), models.Q(('player_one_best_distance__isnull', False), ('player_two_best_distance__isnull', False)), _connector='OR'), name='olympics_distances_pair'),
        ),
    ]
