# Generated by Django 6.1 on 2026-09-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_olympicsmatch_olympicsresult_and_more'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی\u200cشده'), ('active', 'فعال'), ('finished', 'تمام\u200cشده'), ('cancelled', 'لغوشده')], default='scheduled', max_length=10)),
                ('reward', models.PositiveIntegerField(default=1000)),
                ('opening_bid', models.PositiveIntegerField(default=10)),
                ('duration_seconds', models.PositiveIntegerField(default=600)),
                ('ranking_snapshot', models.JSONField(default=list)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('reward__gt', 0)), name='auction_reward_positive'), models.CheckConstraint(condition=models.Q(('opening_bid__gt', 0)), name='auction_opening_positive'), models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='auction_duration_positive'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='auction_window_positive')],
            },
        ),
        migrations.CreateModel(
            name='AuctionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_one', models.PositiveIntegerField()),
                ('rank_two', models.PositiveIntegerField(blank=True, null=True)),
                ('team_one_bid', models.PositiveIntegerField(default=0)),
                ('team_two_bid', models.PositiveIntegerField(default=0)),
                ('highest_bid', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی\u200cشده'), ('active', 'فعال'), ('finished', 'تمام\u200cشده'), ('cancelled', 'لغوشده')], max_length=10)),
                ('automatic_award', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='events.auctionevent')),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leading_auctions', to='teams.team')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions_as_team_one', to='teams.team')),
                ('team_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auctions_as_team_two', to='teams.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_auctions', to='teams.team')),
            ],
            options={
                'ordering': ['rank_one'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('sequence', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('committed_delta', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_bids', to='teams.team')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='events.auctionpair')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PigEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('finished', 'تمام\u200cشده')], default='active', max_length=8)),
                ('entry_fee', models.PositiveIntegerField(default=200)),
                ('max_pot', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('entry_fee__gt', 0)), name='pig_entry_fee_positive'), models.CheckConstraint(condition=models.Q(('max_pot__gt', 0)), name='pig_max_pot_positive')],
            },
        ),
        migrations.CreateModel(
            name='PigGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.PositiveIntegerField()),
                ('max_pot', models.PositiveIntegerField()),
                ('pot', models.PositiveIntegerField(default=0)),
                ('rolls_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('finished_cashed_out', 'برداشت\u200cشده'), ('finished_rolled_one', 'باخت با تاس یک'), ('finished_max_pot', 'رسیدن به سقف')], default='active', max_length=20)),
                ('final_payout', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='events.pigevent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pig_games', to='teams.team')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PigActionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('action', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_receipts', to='events.piggame')),
            ],
        ),
        migrations.CreateModel(
            name='PigRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('number', models.PositiveIntegerField()),
                ('dice_result', models.PositiveSmallIntegerField()),
                ('amount_added', models.PositiveIntegerField(default=0)),
                ('pot_after', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='events.piggame')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WheelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی\u200cشده'), ('active', 'فعال'), ('grand_prize_claimed', 'جایزه بزرگ برنده شد'), ('finished', 'تمام\u200cشده'), ('cancelled', 'لغوشده')], default='scheduled', max_length=19)),
                ('spin_cost', models.PositiveIntegerField(default=10)),
                ('total_collected', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grand_prize_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wheel_grand_prizes', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32)),
                ('prize_type', models.CharField(choices=[('glorium', 'گلوریوم'), ('merchandise', 'کالا'), ('grand_prize', 'جایزه بزرگ')], max_length=11)),
                ('display_name', models.CharField(max_length=100)),
                ('glorium_amount', models.PositiveIntegerField(default=0)),
                ('reward_data', models.JSONField(blank=True, default=dict)),
                ('weight', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('claimed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.wheelevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WheelSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('spin_cost', models.PositiveIntegerField()),
                ('prize_type', models.CharField(choices=[('glorium', 'گلوریوم'), ('merchandise', 'کالا'), ('grand_prize', 'جایزه بزرگ')], max_length=11)),
                ('prize_name', models.CharField(max_length=100)),
                ('glorium_payout', models.PositiveIntegerField(default=0)),
                ('delivery_status', models.CharField(choices=[('not_applicable', 'نامرتبط'), ('pending', 'در انتظار تحویل'), ('delivered', 'تحویل\u200cشده')], default='not_applicable', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='events.wheelevent')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='events.wheelprize')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wheel_spins', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='auctionpair',
            constraint=models.CheckConstraint(condition=models.Q(('team_two__isnull', True), models.Q(('team_one', models.F('team_two')), _negated=True), _connector='OR'), name='auction_pair_distinct_teams'),
        ),
        migrations.AddConstraint(
            model_name='auctionpair',
            constraint=models.UniqueConstraint(fields=('event', 'team_one'), name='auction_unique_team_one'),
        ),
        migrations.AddConstraint(
            model_name='auctionpair',
            constraint=models.UniqueConstraint(fields=('event', 'team_two'), name='auction_unique_team_two'),
        ),
        migrations.AddConstraint(
            model_name='auctionbid',
            constraint=models.UniqueConstraint(fields=('pair', 'sequence'), name='auction_bid_sequence'),
        ),
        migrations.AddConstraint(
            model_name='auctionbid',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='auction_bid_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='auctionbid',
            constraint=models.CheckConstraint(condition=models.Q(('committed_delta__gt', 0)), name='auction_bid_delta_positive'),
        ),
        migrations.AddConstraint(
            model_name='piggame',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('event', 'team'), name='pig_one_active_game_per_team'),
        ),
        migrations.AddConstraint(
            model_name='piggame',
            constraint=models.CheckConstraint(condition=models.Q(('pot__lte', models.F('max_pot'))), name='pig_pot_below_max'),
        ),
        migrations.AddConstraint(
            model_name='pigroll',
            constraint=models.UniqueConstraint(fields=('game', 'number'), name='pig_roll_number'),
        ),
        migrations.AddConstraint(
            model_name='pigroll',
            constraint=models.CheckConstraint(condition=models.Q(('dice_result__gte', 1), ('dice_result__lte', 6)), name='pig_die_range'),
        ),
        migrations.AddConstraint(
            model_name='wheelevent',
            constraint=models.CheckConstraint(condition=models.Q(('spin_cost__gt', 0)), name='wheel_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='wheelprize',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='wheel_prize_code'),
        ),
        migrations.AddConstraint(
            model_name='wheelprize',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='wheel_prize_weight_positive'),
        ),
    ]
