# Generated by Django 6.1 on 2026-09-03 09:23

import django.db.models.deletion
from django.db import migrations, models


def seed_event_configurations(apps, schema_editor):
    configuration = apps.get_model("events", "EventConfiguration")
    rows = [
        ("territory_control", None, {}),
        ("charity_bag", 1800, {}),
        ("centipede", None, {}),
        ("olympics_coin", None, {}),
        (
            "olympics_marble",
            None,
            {
                "scoring_zones": [
                    {"code": "outer", "label": "حلقه بیرونی", "score": 1},
                    {"code": "middle", "label": "حلقه میانی", "score": 3},
                    {"code": "center", "label": "مرکز", "score": 5},
                ]
            },
        ),
        ("limited_auction", 1800, {}),
        ("prize_wheel", None, {}),
        ("pig", None, {}),
    ]
    configuration.objects.bulk_create(
        [
            configuration(code=code, duration_seconds=duration, settings=settings)
            for code, duration, settings in rows
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auctionevent_auctionpair_auctionbid_pigevent_piggame_and_more'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('territory_control', 'نبرد قلمرو'), ('charity_bag', 'کیسه خیریه'), ('centipede', 'بازی هزارپا'), ('olympics_coin', 'سکه نزدیک دیوار'), ('olympics_marble', 'تیله هدف'), ('limited_auction', 'حراج محدود'), ('prize_wheel', 'گردونه شانس'), ('pig', 'بازی خوک')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_seconds__isnull', True), ('duration_seconds__gt', 0), _connector='OR'), name='event_configuration_duration_positive')],
            },
        ),
        migrations.CreateModel(
            name='MatchmakingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(choices=[('territory_control', 'نبرد قلمرو'), ('charity_bag', 'کیسه خیریه'), ('centipede', 'بازی هزارپا'), ('olympics_coin', 'سکه نزدیک دیوار'), ('olympics_marble', 'تیله هدف'), ('limited_auction', 'حراج محدود'), ('prize_wheel', 'گردونه شانس'), ('pig', 'بازی خوک')], max_length=32)),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('matched', 'جفت\u200cشده'), ('cancelled', 'لغوشده')], default='waiting', max_length=10)),
                ('match_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('matched_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_against_tickets', to='teams.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchmaking_tickets', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('event_code', 'team'), name='one_waiting_ticket_per_team_event'), models.CheckConstraint(condition=models.Q(('team', models.F('matched_team')), _negated=True), name='matchmaking_distinct_teams')],
            },
        ),
        migrations.RunPython(seed_event_configurations, migrations.RunPython.noop),
    ]
