# Generated by Django 6.1 on 2026-09-03 20:20

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_olympicsplayerrun"),
        ("teams", "0002_team_color"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="centipedegame",
            name="centipede_status_consistent",
        ),
        migrations.RemoveConstraint(
            model_name="centipedegame",
            name="centipede_payout_matches_winner",
        ),
        migrations.AddField(
            model_name="centipedegame",
            name="pot",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="centipedegame",
            name="production_rounds",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="centipedegame",
            name="rules_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="centipedegame",
            name="rules_version",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="centipededecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("take", "بردار"),
                    ("continue", "ادامه بده"),
                    ("produce", "تولید"),
                    ("split", "توافق"),
                    ("steal", "دزدی"),
                    ("preserve", "قناعت"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="centipedegame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("active_player__isnull", True),
                        ("finished_at__isnull", True),
                        ("player_one_final_payout", 0),
                        ("player_two_final_payout", 0),
                        ("status", "waiting_for_players"),
                        ("winner__isnull", True),
                    ),
                    models.Q(
                        ("finished_at__isnull", True),
                        ("player_one_final_payout", 0),
                        ("player_two_final_payout", 0),
                        ("status", "active"),
                        ("winner__isnull", True),
                    ),
                    models.Q(
                        ("active_player__isnull", True),
                        ("finished_at__isnull", False),
                        ("status", "finished"),
                    ),
                    _connector="OR",
                ),
                name="centipede_status_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="centipedegame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("player_one_final_payout__gt", 0),
                        ("player_two_final_payout", 0),
                        ("winner", models.F("player_one")),
                    ),
                    models.Q(
                        ("player_one_final_payout", 0),
                        ("player_two_final_payout__gt", 0),
                        ("winner", models.F("player_two")),
                    ),
                    ("winner__isnull", True),
                    ("rules_version", 2),
                    _connector="OR",
                ),
                name="centipede_payout_matches_winner",
            ),
        ),
        migrations.AddConstraint(
            model_name="centipedegame",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rules_version", 1),
                    models.Q(
                        (
                            "pot",
                            django.db.models.expressions.CombinedExpression(
                                models.Value(200),
                                "+",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("production_rounds"), "*", models.Value(200)
                                ),
                            ),
                        ),
                        (
                            "pot__gte",
                            django.db.models.expressions.CombinedExpression(
                                models.F("player_one_final_payout"),
                                "+",
                                models.F("player_two_final_payout"),
                            ),
                        ),
                        ("production_rounds__lte", 4),
                        (
                            "round_number",
                            django.db.models.expressions.CombinedExpression(
                                models.F("production_rounds"), "+", models.Value(1)
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="centipede_pool_consistent",
            ),
        ),
    ]
