"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:3000", "http://127.0.0.1:3000"]),
    S3_BUCKET_NAME=(str, ""),
    S3_ACCESS_KEY=(str, ""),
    S3_SECRET_KEY=(str, ""),
    S3_ENDPOINT=(str, ""),
    S3_REGION=(str, "us-east-1"),
    S3_PRESIGNED_EXPIRE=(int, 300),
)
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# SPA is on :3000; Vite proxies /api to :8000. CSRF Origin checks the browser
# origin against this list when Host does not match Origin (e.g. changeOrigin).
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")


# Session/CSRF cookie hardening. The contest is played online by teams over the
# public internet, so these default on; they only come off for a plain-HTTP run
# of the container stack, where DEBUG is off but there is no TLS in front.
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 2 weeks — outlasts the contest
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SECURE_REDIRECT_EXEMPT = [r"^healthz$"]
# Only trust the forwarded-proto header behind our own reverse proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if not DEBUG else None


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "rest_framework",
    "storages",
    # Project
    "teams",
    "accounts",
    "game",
    "notifications",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves STATIC_ROOT: uvicorn is not fronted by a web server, and Django
    # itself only serves /static/ under DEBUG.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Defaults are the zero-setup development stack: SQLite on disk and Django's
# built-in local-memory cache. Set DATABASE_URL / REDIS_URL to point at
# PostgreSQL and Redis (see docker-compose.yml).

DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
}


# Redis. Two separate URLs on purpose: cache.clear() issues FLUSHDB, which
# wipes the whole logical database, so the cache must not share a database
# index with the Streams used for SSE fan-out.

REDIS_URL = env("REDIS_URL", default="")  # Streams / SSE fan-out
REDIS_CACHE_URL = env("REDIS_CACHE_URL", default="")


# Server-sent events. The stream carries hints, not board state: a client that
# receives one refetches through the normal API.

SSE_STREAM_KEY = env("SSE_STREAM_KEY", default="karsoogh:board")
SSE_STREAM_MAXLEN = env.int("SSE_STREAM_MAXLEN", default=1000)
SSE_HEARTBEAT_SECONDS = env.int("SSE_HEARTBEAT_SECONDS", default=15)
SSE_RETRY_MS = env.int("SSE_RETRY_MS", default=2500)
SSE_RETRY_JITTER_MS = env.int("SSE_RETRY_JITTER_MS", default=2000)
SSE_QUEUE_MAXSIZE = env.int("SSE_QUEUE_MAXSIZE", default=32)
SSE_BLOCK_MS = env.int("SSE_BLOCK_MS", default=5000)
SSE_REPLAY_LIMIT = env.int("SSE_REPLAY_LIMIT", default=100)


# Cache. Falls back to Django's local-memory cache in development.

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "karsoogh",
    },
}

if REDIS_CACHE_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_CACHE_URL,
        },
    }


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    # Session cookies, same domain — no JWT to expire mid-contest.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # The browsable API is a development convenience; production serves JSON only.
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    # ScopedRateThrottle is a no-op on views without throttle_scope, so this
    # only bites on login. Counters live in CACHES["default"] — LocMemCache
    # is per-process, so set REDIS_CACHE_URL in multi-worker deployments or
    # the 10/min cap is not actually shared.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/min",
    },
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
        "rest_framework.renderers.BrowsableAPIRenderer"
    )

    # OpenAPI schema + Swagger UI. Development only — drf-spectacular is a dev
    # dependency, so nothing here is imported in production.
    INSTALLED_APPS += ["drf_spectacular"]
    REST_FRAMEWORK["DEFAULT_SCHEMA_CLASS"] = "drf_spectacular.openapi.AutoSchema"

    SPECTACULAR_SETTINGS = {
        "TITLE": "Karsoogh 26 Competition API",
        "DESCRIPTION": "Session cookie auth. GET /api/auth/csrf/ first; send X-CSRFToken on POST.",
        "VERSION": "0.1.0",
        "SERVE_INCLUDE_SCHEMA": False,
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Leading slash is required: without it StaticFilesHandler does not match
# /static/... and admin CSS/JS 404 in development.
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

MAX_UPLOAD_BYTES = 10 * 1024 * 1024


# Media goes to S3 (or any S3-compatible endpoint) as soon as a bucket is named;
# with S3_BUCKET_NAME empty everything falls back to MEDIA_ROOT on disk, which is
# what development and the test suite run on.
S3_BUCKET_NAME = env("S3_BUCKET_NAME")
S3_ACCESS_KEY = env("S3_ACCESS_KEY")
S3_SECRET_KEY = env("S3_SECRET_KEY")
S3_ENDPOINT = env("S3_ENDPOINT") or None
S3_REGION = env("S3_REGION")
S3_PRESIGNED_EXPIRE = env("S3_PRESIGNED_EXPIRE")

USE_S3_MEDIA = bool(S3_BUCKET_NAME)

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

if USE_S3_MEDIA:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": S3_ACCESS_KEY,
            "secret_key": S3_SECRET_KEY,
            "bucket_name": S3_BUCKET_NAME,
            "endpoint_url": S3_ENDPOINT,
            "region_name": S3_REGION,
            # MinIO and most self-hosted gateways do not do virtual-host
            # buckets, and only sign v4.
            "addressing_style": "path",
            "signature_version": "s3v4",
            "file_overwrite": False,
            "default_acl": None,
            "querystring_auth": True,
            "querystring_expire": S3_PRESIGNED_EXPIRE,
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# karsoogh.* has no handler unless we give it one: a non-django logger
# otherwise propagates to a root logger that Django did not configure for it,
# and the failed-login warnings vanish.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "karsoogh": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
