# Generated by Django 6.1 on 2026-09-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0023_floorreward_duel_cost_override_and_more'),
        ('teams', '0009_alter_balanceevent_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='How organisers recognise this room.', max_length=64)),
                ('link', models.URLField(help_text='The Skyroom meeting URL. Only the two teams and the judge ever see it.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to take the room out of rotation without losing its duels.')),
                ('last_assigned_at', models.DateTimeField(blank=True, help_text='Stamped when the room is handed a duel. Never-used rooms are picked first.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(help_text='The judge who runs this room. Must hold judge_duel.', on_delete=django.db.models.deletion.PROTECT, related_name='duel_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(help_text='Snapshot of the contested floor.')),
                ('stake', models.PositiveIntegerField(help_text='What the attacker paid up front. Refunded on a win, paid to the defender on a loss.')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attacked', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duels_received', to='teams.team')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duels_started', to='teams.team')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duels_lost', to='teams.team')),
                ('mentor', models.ForeignKey(help_text="Snapshot of the room's judge, so repointing a room never rewrites history.", on_delete=django.db.models.deletion.PROTECT, related_name='judged_duels', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duels', to='game.node')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_duels', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text="The defender's seat being contested. Handed to the attacker on a loss.", on_delete=django.db.models.deletion.PROTECT, related_name='duels', to='game.occupancy')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duels_won', to='teams.team')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duels', to='duels.room')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'permissions': [('judge_duel', 'Can judge duels')],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['last_assigned_at'], name='room_rotation_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('link',), name='room_link_unique'),
        ),
        migrations.AddIndex(
            model_name='duel',
            index=models.Index(condition=models.Q(('status', 'open')), fields=['mentor'], name='duel_open_by_mentor_idx'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.CheckConstraint(condition=models.Q(('attacker', models.F('attacked')), _negated=True), name='duel_two_distinct_teams'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('loser__isnull', True), ('resolved_at__isnull', True), ('status', 'open'), ('winner__isnull', True)), models.Q(('loser__isnull', False), ('resolved_at__isnull', False), ('status', 'closed'), ('winner__isnull', False)), _connector='OR'), name='duel_status_consistent'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.CheckConstraint(condition=models.Q(('winner__isnull', True), ('winner', models.F('attacker')), ('winner', models.F('attacked')), _connector='OR'), name='duel_winner_is_participant'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.CheckConstraint(condition=models.Q(('loser__isnull', True), ('loser', models.F('attacker')), ('loser', models.F('attacked')), _connector='OR'), name='duel_loser_is_participant'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.CheckConstraint(condition=models.Q(('winner__isnull', True), models.Q(('winner', models.F('loser')), _negated=True), _connector='OR'), name='duel_winner_is_not_loser'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('attacker',), name='duel_one_open_per_attacker'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('attacked',), name='duel_one_open_per_attacked'),
        ),
        migrations.AddConstraint(
            model_name='duel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('target',), name='duel_one_open_per_target'),
        ),
    ]
