# Generated by Django 6.1 on 2026-09-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('announcement', 'پیام مدیر'), ('system', 'خودکار')], default='announcement', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال\u200cشده')], default='draft', max_length=8)),
                ('sender_label', models.CharField(blank=True, help_text='What recipients see as the sender; survives the account being deleted.', max_length=64)),
                ('audience', models.CharField(choices=[('all', 'همه'), ('teams', 'همهٔ تیم\u200cها'), ('mentors', 'همهٔ منتورها'), ('designers', 'همهٔ طراحان'), ('team', 'یک تیم'), ('user', 'یک نفر')], default='all', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('event_key', models.SlugField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('audience_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressed_messages', to='teams.team')),
                ('audience_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressed_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='Null for automatic messages: the game itself has no user row.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('send_announcement', 'Can send announcements')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', '-created_at'], name='message_status_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience', 'team'), ('audience_team__isnull', False)), models.Q(models.Q(('audience', 'team'), _negated=True), ('audience_team__isnull', True)), _connector='OR'), name='message_team_audience_has_team'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience', 'user'), ('audience_user__isnull', False)), models.Q(models.Q(('audience', 'user'), _negated=True), ('audience_user__isnull', True)), _connector='OR'), name='message_user_audience_has_user'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', True), ('status', 'draft')), models.Q(('sent_at__isnull', False), ('status', 'sent')), _connector='OR'), name='message_sent_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'system'), _negated=True), ('status', 'sent'), _connector='OR'), name='message_system_is_never_draft'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('read_at__isnull', True)), fields=['user'], name='notification_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-id'], name='notification_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='notification_once_per_user'),
        ),
    ]
