# Generated by Django 6.1 on 2026-09-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_audience_sets'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_team_audience_has_team',
        ),
        migrations.RemoveConstraint(
            model_name='message',
            name='message_user_audience_has_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='message',
            name='audience_team',
        ),
        migrations.RemoveField(
            model_name='message',
            name='audience_user',
        ),
    ]
