"""Drop the automatic half of the inbox.

The board used to narrate itself — "your answer scored 90", "your time ran
out", "the game started". It was removed on request: a notification per board
event is noise, and noise is how a player learns to ignore the bell. What the
board did is visible on the board.

Nothing writes a system message any more, so `kind` and `event_key` can only
ever hold their defaults. The rows those columns described go with them: they
narrate a run that is over, and leaving them would strand messages with no
sender in everyone's inbox. Hand-written announcements are untouched.

Irreversible in the sense that matters — the reverse restores the columns but
not the deleted rows, which is the honest outcome for content that only the
deleted code could produce.
"""

# Generated by Django 6.1 on 2026-09-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def drop_system_messages(apps, schema_editor):
    """Notification rows cascade off the messages."""
    apps.get_model("notifications", "Message").objects.filter(kind="system").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_drop_single_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_system_messages, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="message",
            name="message_system_is_never_draft",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Nulled if the account is later deleted; sender_label survives.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="event_key",
        ),
        migrations.RemoveField(
            model_name="message",
            name="kind",
        ),
    ]
