"""Retire automatic-message fields without deleting existing inbox history.

Automatic generation is disabled in application code. Historical messages and
their recipient/read records must survive deployment, per the migration policy.
Already-applied copies of the old destructive migration cannot restore lost rows.
"""

# Generated by Django 6.1 on 2026-09-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_drop_single_audience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="message_system_is_never_draft",
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                help_text="Nulled if the account is later deleted; sender_label survives.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="event_key",
        ),
        migrations.RemoveField(
            model_name="message",
            name="kind",
        ),
    ]
