# Generated by Django 6.1 on 2026-09-02 15:28

import django.db.models.deletion
import minesweeper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=8)),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('mine_count', models.PositiveSmallIntegerField()),
                ('board', models.JSONField(default=minesweeper.models.empty_board, help_text='Server-side grid: {cells: [[{mine, revealed, flagged, adjacent_mines}, ...], ...]}. Do not expose unrevealed mines to teams.')),
                ('status', models.CharField(choices=[('in_progress', 'در حال اجرا'), ('won', 'برنده'), ('lost', 'باخته')], default='in_progress', max_length=12)),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minesweeper_games', to='teams.team')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['team', 'status'], name='msweeper_team_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('difficulty', 'easy'), ('height', 9), ('mine_count', 10), ('width', 9)), models.Q(('difficulty', 'medium'), ('height', 16), ('mine_count', 40), ('width', 16)), models.Q(('difficulty', 'hard'), ('height', 16), ('mine_count', 99), ('width', 30)), _connector='OR'), name='minesweepergame_layout_matches_difficulty'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'in_progress')), models.Q(('finished_at__isnull', False), ('status__in', ['won', 'lost'])), _connector='OR'), name='minesweepergame_finished_at_matches_status')],
            },
        ),
    ]
