# Generated by Django 6.1 on 2026-09-03 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0002_minesweepergame_node'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minesweepergame',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minesweeper_games', to='teams.team'),
        ),
    ]
