# Generated by Django 6.1 on 2026-09-03 08:32

import django.db.models.deletion
import minesweeper.models
from django.db import migrations, models


def _split_boards_and_copy_attempts(apps, schema_editor):
    Game = apps.get_model("minesweeper", "MinesweeperGame")
    Attempt = apps.get_model("minesweeper", "MinesweeperAttempt")
    for game in Game.objects.all():
        cells = (game.board or {}).get("cells") or []
        layout_cells = []
        progress_cells = []
        for row in cells:
            layout_row = []
            progress_row = []
            for cell in row:
                layout_row.append(
                    {
                        "mine": bool(cell.get("mine", False)),
                        "adjacent_mines": int(cell.get("adjacent_mines", 0)),
                    }
                )
                progress_row.append(
                    {
                        "revealed": bool(cell.get("revealed", False)),
                        "flagged": bool(cell.get("flagged", False)),
                    }
                )
            layout_cells.append(layout_row)
            progress_cells.append(progress_row)
        game.board = {"cells": layout_cells}
        game.save(update_fields=["board"])
        if game.team_id:
            Attempt.objects.create(
                game=game,
                team_id=game.team_id,
                status=game.status,
                board={"cells": progress_cells},
                score=game.score,
                finished_at=game.finished_at,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0003_minesweepergame_team_nullable'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'در حال اجرا'), ('won', 'برنده'), ('lost', 'باخته')], default='in_progress', max_length=12)),
                ('board', models.JSONField(default=minesweeper.models.empty_progress_board, help_text='Per-attempt progress: {cells: [[{revealed, flagged}, ...], ...]}. Mine locations stay on the game layout.')),
                ('score', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='minesweepergame',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='minesweepergame',
            name='minesweepergame_finished_at_matches_status',
        ),
        migrations.RemoveIndex(
            model_name='minesweepergame',
            name='msweeper_team_status_idx',
        ),
        migrations.AlterField(
            model_name='minesweepergame',
            name='board',
            field=models.JSONField(default=minesweeper.models.empty_layout_board, help_text='Mine layout only: {cells: [[{mine, adjacent_mines}, ...], ...]}. Do not expose this JSON to teams while an attempt is in progress.'),
        ),
        migrations.AddField(
            model_name='minesweeperattempt',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='minesweeper.minesweepergame'),
        ),
        migrations.AddField(
            model_name="minesweeperattempt",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="minesweeper_attempts",
                to="teams.team",
            ),
        ),
        migrations.RunPython(_split_boards_and_copy_attempts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='score',
        ),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='status',
        ),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='team',
        ),
        migrations.AddIndex(
            model_name='minesweeperattempt',
            index=models.Index(fields=['team', 'status'], name='msweeper_att_team_status_idx'),
        ),
        migrations.AddIndex(
            model_name='minesweeperattempt',
            index=models.Index(fields=['game', 'team'], name='msweeper_att_game_team_idx'),
        ),
        migrations.AddConstraint(
            model_name='minesweeperattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'in_progress')), models.Q(('finished_at__isnull', False), ('status__in', ['won', 'lost'])), _connector='OR'), name='minesweeperattempt_finished_at_matches_status'),
        ),
    ]
