# Generated by Django 6.1 on 2026-09-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0004_minesweeper_attempt'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='minesweeperattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('game',), name='one_active_attempt_per_game'),
        ),
    ]
