# Generated by Django 6.1 on 2026-09-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_level_attempt_ttl'),
        ('minesweeper', '0005_one_active_attempt_per_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinesweeperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Minesweeper settings',
            },
        ),
        migrations.RemoveConstraint(
            model_name='minesweeperattempt',
            name='one_active_attempt_per_game',
        ),
        migrations.AddField(
            model_name='minesweepersettings',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minesweeper_settings', to='game.node'),
        ),
    ]
