# Generated by Django 6.1 on 2026-09-04 22:02

from django.db import migrations

# Layout numbers that 0007 seeded (without the retired base_score). `seed` is
# called by name from conftest after a transactional test flushes the tables;
# this migration's operations do not run it.
SEED = [
    ("easy", "آسان", 9, 9, 10, 10),
    ("medium", "متوسط", 16, 16, 40, 20),
    ("hard", "سخت", 30, 16, 99, 30),
]


def seed(apps, schema_editor):
    """Put the shipped difficulties back after a transactional-test flush."""
    DifficultyConfig = apps.get_model("minesweeper", "DifficultyConfig")
    for key, label, width, height, mine_count, sort_order in SEED:
        DifficultyConfig.objects.get_or_create(
            key=key,
            defaults={
                "label": label,
                "width": width,
                "height": height,
                "mine_count": mine_count,
                "sort_order": sort_order,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('minesweeper', '0008_seed_toll_boards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='difficultyconfig',
            name='base_score',
        ),
        migrations.RemoveField(
            model_name='minesweeperattempt',
            name='score',
        ),
        migrations.RemoveField(
            model_name='minesweepergame',
            name='base_score',
        ),
    ]
