# Generated by Django 6.1 on 2026-08-23 21:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_ttl_minutes", models.PositiveSmallIntegerField(default=15)),
                ("duel_cooldown_minutes", models.PositiveSmallIntegerField(default=10)),
                ("duel_deadline_minutes", models.PositiveSmallIntegerField(default=15)),
                ("initial_balance", models.PositiveIntegerField(default=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "شروع نشده"),
                            ("running", "در حال اجرا"),
                            ("paused", "متوقف"),
                            ("finished", "تمام شده"),
                        ],
                        default="not_started",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "game settings",
                "verbose_name_plural": "game settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="gamesettings_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GradeMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.PositiveSmallIntegerField(unique=True)),
                ("factor", models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                "ordering": ["grade"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("grade__lte", 100)),
                        name="grademultiplier_grade_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("factor__gte", 0), ("factor__lte", 1)),
                        name="grademultiplier_factor_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LevelConfig",
            fields=[
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("spawn", "شروع"),
                            ("easy", "آسان"),
                            ("medium", "متوسط"),
                            ("hard", "سخت"),
                        ],
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField()),
                ("entry_cost", models.PositiveIntegerField()),
                ("networth_base", models.IntegerField(default=0)),
                (
                    "networth_factor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "duel_factor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2"), max_digits=5
                    ),
                ),
                (
                    "buyout_factor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("4"), max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "level config",
                "verbose_name_plural": "level configs",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("capacity__gte", 1), ("capacity__lte", 3)),
                        name="levelconfig_capacity_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=64)),
                (
                    "level",
                    models.ForeignKey(
                        db_column="level",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="game.levelconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FloorReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.PositiveSmallIntegerField()),
                ("points", models.IntegerField()),
                (
                    "level",
                    models.ForeignKey(
                        db_column="level",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_rewards",
                        to="game.levelconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "floor"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "floor"), name="uniq_level_floor"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("floor__gte", 1), ("floor__lte", 3)),
                        name="floorreward_floor_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_a",
                        to="game.node",
                    ),
                ),
                (
                    "b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_b",
                        to="game.node",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("a", "b"), name="edge_unique"),
                    models.CheckConstraint(
                        condition=models.Q(("a__lt", models.F("b"))),
                        name="edge_normalised",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Occupancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot", models.PositiveSmallIntegerField()),
                ("floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "grade_multiplier",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Snapshot of the curve at judging time, so points stay reproducible.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("question_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("points_awarded", models.IntegerField(default=0)),
                ("is_spawn", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("zero_grade", "نمره صفر"),
                            ("expired", "منقضی شد"),
                            ("duel_lost", "باخت دوئل"),
                            ("bought_out", "خریداری شد"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupancies",
                        to="game.node",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupancies",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "occupancies",
                "indexes": [
                    models.Index(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=["expires_at"],
                        name="occ_active_expiry_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("node", "slot"),
                        name="occ_one_team_per_slot",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("node", "floor"),
                        name="occ_one_team_per_floor",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("team", "node"),
                        name="occ_one_unit_per_team",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("slot__gte", 1), ("slot__lte", 3)),
                        name="occ_slot_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("grade__isnull", True),
                            ("grade__lte", 100),
                            _connector="OR",
                        ),
                        name="occ_grade_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("grade__isnull", True),
                            ("question_assigned_at__isnull", False),
                            _connector="OR",
                        ),
                        name="occ_graded_has_assigned_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("grade__isnull", True),
                            ("grade_multiplier__isnull", False),
                            _connector="OR",
                        ),
                        name="occ_graded_has_multiplier",
                    ),
                ],
            },
        ),
    ]
