# Generated by Django 6.1 on 2026-08-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_seed_economy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occupancy",
            options={
                "permissions": [("act_as_mentor", "Can perform mentor actions")],
                "verbose_name_plural": "occupancies",
            },
        ),
        migrations.RemoveField(
            model_name="occupancy",
            name="points_awarded",
        ),
    ]
