# Generated by Django 6.1 on 2026-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_questions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="edge",
            name="edge_normalised",
        ),
        migrations.AddField(
            model_name="edge",
            name="directed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="levelconfig",
            name="level",
            field=models.CharField(
                choices=[
                    ("spawn", "شروع"),
                    ("easy", "آسان"),
                    ("medium", "متوسط"),
                    ("hard", "سخت"),
                    ("toll", "عوارضی"),
                ],
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("directed", True), ("a__lt", models.F("b")), _connector="OR"
                ),
                name="edge_normalised",
            ),
        ),
    ]
