# Generated by Django 6.1 on 2026-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_seed_toll_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="leaderboard_public",
            field=models.BooleanField(default=False),
        ),
    ]
