# Generated by Django 6.1 on 2026-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    # Ordered after the entry sheet, which adds `started_at` for the same reason
    # this branch does: merged, the column must be added exactly once.
    dependencies = [
        ('game', '0009_entry_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Planned finish. Drives the countdown every team sees; purely informational.', null=True),
        ),
    ]
