# Generated by Django 6.1 on 2026-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_leaderboard_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Planned finish. Drives the countdown every team sees; purely informational.', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Stamped the first time status becomes running; anchors the elapsed clock.', null=True),
        ),
    ]
