# Generated by Django 6.1 on 2026-09-02 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_leaderboard_public'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Slot on the sheet, 1-based.')),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['team', 'position'],
            },
        ),
        migrations.CreateModel(
            name='EntryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown')),
                ('answer', models.IntegerField(help_text='Never serialised to a team.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='entry_grace_minutes',
            field=models.PositiveSmallIntegerField(default=20, help_text='Minutes after kick-off when every team may take a spawn regardless.'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='entry_question_count',
            field=models.PositiveSmallIntegerField(default=3, help_text="How many questions land on each team's entry sheet."),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='entry_required_correct',
            field=models.PositiveSmallIntegerField(default=2, help_text='Correct answers needed to unlock the start node.'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Stamped the first time status becomes running; anchors the entry grace.', null=True),
        ),
        migrations.AddConstraint(
            model_name='gamesettings',
            constraint=models.CheckConstraint(condition=models.Q(('entry_required_correct__lte', models.F('entry_question_count'))), name='gamesettings_entry_required_within_sheet'),
        ),
        migrations.AddField(
            model_name='entryattempt',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_attempts', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='entryquestion',
            index=models.Index(fields=['is_active'], name='entryquestion_active_idx'),
        ),
        migrations.AddField(
            model_name='entryattempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='game.entryquestion'),
        ),
        migrations.AddIndex(
            model_name='entryattempt',
            index=models.Index(fields=['team', 'is_correct'], name='entryattempt_team_correct_idx'),
        ),
        migrations.AddConstraint(
            model_name='entryattempt',
            constraint=models.UniqueConstraint(fields=('team', 'question'), name='entryattempt_no_repeat'),
        ),
        migrations.AddConstraint(
            model_name='entryattempt',
            constraint=models.UniqueConstraint(fields=('team', 'position'), name='entryattempt_one_per_position'),
        ),
        migrations.AddConstraint(
            model_name='entryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='entryattempt_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='entryattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answer__isnull', True), ('answered_at__isnull', True), ('is_correct__isnull', True)), models.Q(('answer__isnull', False), ('answered_at__isnull', False), ('is_correct__isnull', False)), _connector='OR'), name='entryattempt_answer_recorded_together'),
        ),
    ]
