# Generated by Django 6.1 on 2026-09-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_clock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesettings',
            options={'permissions': [('control_game', 'Can start, pause, restart and configure the game')], 'verbose_name': 'game settings', 'verbose_name_plural': 'game settings'},
        ),
    ]
