# Generated by Django 6.1 on 2026-09-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_entry_questions'),
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entryattempt',
            name='entryattempt_one_per_position',
        ),
        migrations.AddField(
            model_name='entryattempt',
            name='replaced_at',
            field=models.DateTimeField(blank=True, help_text='Set when the team swapped this question for another one.', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='entry_max_refreshes',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many wrongly-answered entry questions a team may swap for a fresh one, over the whole sheet. Raise it to be more forgiving; 0 disables swapping.'),
        ),
        migrations.AddConstraint(
            model_name='entryattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('replaced_at__isnull', True)), fields=('team', 'position'), name='entryattempt_one_per_position'),
        ),
        migrations.AddConstraint(
            model_name='entryattempt',
            constraint=models.CheckConstraint(condition=models.Q(('replaced_at__isnull', True), ('is_correct', False), _connector='OR'), name='entryattempt_only_wrong_is_replaced'),
        ),
    ]
