# Generated by Django 6.1 on 2026-09-02 13:15

from django.db import migrations, models
from django.utils import timezone


def open_stretch_for_a_running_game(apps, schema_editor):
    """A game already running when the ledger arrived has no open stretch.

    Without this its elapsed timer would sit at zero until somebody paused and
    resumed, because the ledger only rolls on a status change.
    """
    GameSettings = apps.get_model("game", "GameSettings")
    now = timezone.now()
    for row in GameSettings.objects.filter(status="running", running_since__isnull=True):
        row.running_since = row.started_at or now
        row.save(update_fields=["running_since"])


def close_stretch(apps, schema_editor):
    apps.get_model("game", "GameSettings").objects.update(running_since=None)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_god_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesettings',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Seconds the game has spent in the running state, excluding pauses.'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=180, help_text='Total playing time. The countdown is this minus elapsed; 0 turns it off.'),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='running_since',
            field=models.DateTimeField(blank=True, help_text='Start of the current running stretch; null whenever the game is not running.', null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Stamped the first time status becomes running. Informational.', null=True),
        ),
            migrations.RunPython(open_stretch_for_a_running_game, close_stretch),
    ]
