# Generated by Django 6.1 on 2026-09-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_game_run_ledger"),
        ("game", "0013_level_attempt_ttl"),
    ]

    operations = []
