# Generated by Django 6.1 on 2026-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_merge_0012_game_run_ledger_0013_level_attempt_ttl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesettings",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamped the first time status becomes running; anchors the entry grace.",
                null=True,
            ),
        ),
    ]
