# Generated by Django 6.1 on 2026-09-03 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_gamesettings_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='archetype',
            field=models.CharField(blank=True, choices=[('mint', 'ضراب\u200cخانه'), ('cityhall', 'شهرداری'), ('bakery', 'نانوایی'), ('restaurant', 'رستوران'), ('school', 'مدرسه'), ('icecream', 'بستنی\u200cفروشی'), ('newspaper', 'روزنامهٔ گیل\u200cبهشت'), ('hotel', 'مهمان\u200cسرا'), ('caravanserai', 'کاروانسرا'), ('stadium', 'زمین چولیگان'), ('farm', 'زمین کشاورزی'), ('guardpost', 'نگهبانی دیوار'), ('observatory', 'رصدخانه'), ('grocery', 'بقالی'), ('dairy', 'گاوداری'), ('stable', 'اسب\u200cداری'), ('hospital', 'شفاخانه'), ('courthouse', 'دادسرا'), ('ministry', 'وزارتخانه'), ('mine', 'معدن'), ('trade', 'تجارت\u200cخانه'), ('industry', 'کارخانه'), ('sawmill', 'کارگاه چوب\u200cبری'), ('tailor', 'کارگاه لباس\u200cدوزی'), ('smithy', 'کارگاه آهنگری'), ('library', 'کتابخانه')], max_length=32),
        ),
        migrations.CreateModel(
            name='MapDesign',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('road_style', models.CharField(choices=[('straight', 'مستقیم'), ('curved', 'منحنی'), ('dashed', 'خط\u200cچین')], default='straight', max_length=12)),
                ('tint_strength', models.PositiveSmallIntegerField(default=8, help_text='How strongly each sector is washed with its colour, 0–100.')),
                ('halo_strength', models.PositiveSmallIntegerField(default=45, help_text='Opacity of the neighbourhood ring around every node, 0–100.')),
            ],
            options={
                'verbose_name': 'map design',
                'verbose_name_plural': 'map design',
                'permissions': [('design_map', "Can edit the map's look")],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='mapdesign_singleton'), models.CheckConstraint(condition=models.Q(('tint_strength__lte', 100)), name='mapdesign_tint_range'), models.CheckConstraint(condition=models.Q(('halo_strength__lte', 100)), name='mapdesign_halo_range')],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('theme', models.CharField(choices=[('water', 'آبی — آب'), ('fire', 'قرمز — آتش'), ('lightning', 'نارنجی — رعد و برق'), ('history', 'سبز — باستان\u200cشناسی'), ('sport', 'زرد — ورزش'), ('knowledge', 'بنفش — دانش'), ('unbuilt', 'سفید — نیمه\u200cساخته'), ('tribal', 'خاکستری — قبیله\u200cای'), ('soil', 'قهوه\u200cای — خاک')], max_length=16)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-f]{6}$', 'Color must be a lowercase #rrggbb hex.')])),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.CheckConstraint(condition=models.Q(('index__gte', 0), ('index__lt', 8)), name='neighborhood_index_range')],
            },
        ),
    ]
