# Generated by Django 6.1 on 2026-09-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_stronger_neighbourhood_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancy',
            name='source',
            field=models.CharField(choices=[('attempt', 'تلاش'), ('item', 'آیتم')], default='attempt', max_length=16),
        ),
    ]
