# Generated by Django 6.1 on 2026-09-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_occupancy_acquisition_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancy',
            name='release_reason',
            field=models.CharField(blank=True, choices=[('zero_grade', 'نمره صفر'), ('expired', 'منقضی شد'), ('duel_lost', 'باخت دوئل'), ('bought_out', 'خریداری شد'), ('item_takeover', 'آیتم')], max_length=16),
        ),
    ]
