# Generated by Django 6.1 on 2026-09-04 14:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_question_body_optional_answer_type_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorreward',
            name='duel_cost_override',
            field=models.PositiveIntegerField(blank=True, help_text="What a duel for this floor costs. Leave empty to fall back to the level's duel factor times the floor's points.", null=True),
        ),
        migrations.AlterField(
            model_name='levelconfig',
            name='duel_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('2'), help_text="Fallback duel price: this times the floor's points, when the floor has no override.", max_digits=5),
        ),
        migrations.AlterField(
            model_name='occupancy',
            name='source',
            field=models.CharField(choices=[('attempt', 'تلاش'), ('item', 'آیتم'), ('duel', 'دوئل')], default='attempt', max_length=16),
        ),
    ]
