# Generated by Django 6.1 on 2026-09-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_question_max_grade"),
        ("game", "0022_question_body_optional_answer_type_default"),
    ]

    operations = []
