# Generated by Django 6.1 on 2026-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_merge_20260904_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupancy",
            name="release_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zero_grade", "نمره صفر"),
                    ("partial_grade", "نمره ناقص"),
                    ("expired", "منقضی شد"),
                    ("duel_lost", "باخت دوئل"),
                    ("bought_out", "خریداری شد"),
                    ("item_takeover", "آیتم"),
                ],
                max_length=16,
            ),
        ),
    ]
