# Generated by Django 6.1 on 2026-09-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0024_alter_occupancy_release_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="levelconfig",
            name="level",
            field=models.CharField(
                choices=[
                    ("spawn", "شروع"),
                    ("easy", "آسان"),
                    ("medium", "متوسط"),
                    ("hard", "سخت"),
                    ("center", "مرکز شهر"),
                    ("toll", "عوارضی"),
                ],
                max_length=8,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
