# Generated by Django 6.1 on 2026-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_seed_duel_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='duel_cooldown_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minutes a team must rest after a duel before it may take part in another.'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='duel_deadline_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Unused. Duel timing is run by the judge in the meeting, not by the server: a team that does not show up is simply not named as the winner.'),
        ),
    ]
