# Generated by Django 6.1 on 2026-09-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0026_seed_center_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesettings",
            name="design_locked",
            field=models.BooleanField(
                default=False,
                help_text="Freeze the map's look. While on, Designers may not write the design and the design pages disappear for them.",
            ),
        ),
    ]
