# Generated by Django 6.1 on 2026-09-05 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0034_acquisition_source_buyout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="The mentor who grades submissions for this question. Unassigned stays in every mentor's queue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grading_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["mentor"], name="question_mentor_idx"),
        ),
    ]
