# Generated by Django 6.1 on 2026-09-05 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0035_question_mentor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="The mentor who grades submissions for this question. Empty = hidden from every mentor queue.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grading_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
