# Generated by Django 6.1 on 2026-09-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0035_node_gelled"),
        ("game", "0037_question_mentors"),
    ]

    operations = []
