# Generated by Django 6.1 on 2026-09-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_merge_0035_node_gelled_0037_question_mentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text="When the current pause began; null while running. On resume, every live attempt's clock is pushed forward by how long this pause lasted, so a question timer freezes with the game instead of burning through the stop.", null=True),
        ),
    ]
