# Generated by Django 6.1 on 2026-08-30 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9a-f]{6}$', 'Color must be a lowercase #rrggbb hex.')]),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False)), fields=('color',), name='team_color_unique_when_set'),
        ),
    ]
