# Generated by Django 6.1 on 2026-09-03 15:33

import django.db.models.deletion
from django.db import migrations, models


def _table_exists(schema_editor, table: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return table in connection.introspection.table_names(cursor)


class CreateModelIfMissing(migrations.CreateModel):
    """Create the table on an existing database; no-op if it is already there.

    This branch only *adds* `BalanceEvent`. After merge onto main, `migrate`
    is enough — rows in Team / Occupancy stay put and the database is not
    rebuilt. A leftover table from an earlier attempt on this branch is kept.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if _table_exists(schema_editor, model._meta.db_table):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        if not _table_exists(schema_editor, model._meta.db_table):
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_team_color"),
    ]

    operations = [
        CreateModelIfMissing(
            name="BalanceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("initial", "موجودی اولیه"),
                            ("entry", "رزرو خانه"),
                            ("grade", "نمره خانه"),
                        ],
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_events",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["team", "created_at"],
                        name="balance_event_team_time",
                    )
                ],
            },
        ),
    ]
