# Generated by Django 6.1 on 2026-09-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('initial', 'موجودی اولیه'), ('entry', 'رزرو خانه'), ('grade', 'نمره خانه')], max_length=16)),
                ('detail', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_events', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['team', 'created_at'], name='balance_event_team_time')],
            },
        ),
    ]
