# Generated by Django 6.1 on 2026-09-03 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_seed_balance_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('fake_document', 'سند جعلی'), ('gel', 'ژل'), ('gilari_100', '۱۰۰ گیلاری')], max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='teams.team')),
            ],
            options={
                'ordering': ['team', 'item_type'],
                'constraints': [models.UniqueConstraint(fields=('team', 'item_type'), name='teamitem_one_per_type')],
            },
        ),
    ]
