# Generated by Django 6.1 on 2026-09-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamitem',
            name='item_type',
            field=models.CharField(choices=[('fake_document', 'سند جعلی'), ('gel', 'گل'), ('gilari_100', '۱۰۰ گیلاری')], max_length=16),
        ),
    ]
