# Generated by Django 6.1 on 2026-09-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_teamitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceevent',
            name='reason',
            field=models.CharField(choices=[('initial', 'موجودی اولیه'), ('entry', 'رزرو خانه'), ('toll', 'عوارضی'), ('grade', 'نمره خانه')], max_length=16),
        ),
    ]
