# Generated by Django 6.1 on 2026-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_balance_reason_toll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceevent',
            name='reason',
            field=models.CharField(choices=[('initial', 'موجودی اولیه'), ('entry', 'رزرو خانه'), ('toll', 'عوارضی'), ('grade', 'نمره خانه'), ('event', 'رویداد'), ('duel', 'دوئل')], max_length=16),
        ),
    ]
