# Generated by Django 6.1 on 2026-09-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_balance_reason_weak_reasoning"),
        ("teams", "0012_gel_label"),
    ]

    operations = []
